# Generated by Django 5.2.13 on 2026-05-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceextraction',
            name='movement_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('tipo', models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], max_length=16)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['tipo', 'descricao', 'id'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'descricao'), name='uniq_classificacao_tipo_descricao')],
            },
        ),
        migrations.CreateModel(
            name='MovimentoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('tipo', models.CharField(choices=[('APAGAR', 'Contas a pagar'), ('ARECEBER', 'Contas a receber')], db_index=True, max_length=16)),
                ('numero_documento', models.CharField(max_length=64)),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('dados_extraidos', models.JSONField(blank=True, default=dict)),
                ('classificacoes', models.ManyToManyField(blank=True, related_name='movimentos', to='invoices.classificacao')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invoiceextraction',
            name='movimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='invoices.movimentocontas'),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, default='', max_length=32)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('numero', models.CharField(blank=True, default='', max_length=32)),
                ('bairro', models.CharField(blank=True, default='', max_length=128)),
                ('municipio', models.CharField(blank=True, default='', max_length=128)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('cep', models.CharField(blank=True, default='', max_length=16)),
                ('telefone', models.CharField(blank=True, default='', max_length=32)),
                ('is_cliente', models.BooleanField(default=False)),
                ('is_fornecedor', models.BooleanField(default=False)),
                ('is_faturado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['razao_social', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_cliente__in', [True, False])), name='chk_pessoa_is_cliente_bool'), models.CheckConstraint(condition=models.Q(('is_fornecedor__in', [True, False])), name='chk_pessoa_is_fornecedor_bool'), models.CheckConstraint(condition=models.Q(('is_faturado__in', [True, False])), name='chk_pessoa_is_faturado_bool')],
            },
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='faturado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_faturados', to='invoices.pessoa'),
        ),
        migrations.AddField(
            model_name='movimentocontas',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_principais', to='invoices.pessoa'),
        ),
        migrations.CreateModel(
            name='ParcelaContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('identificacao', models.CharField(blank=True, default='', max_length=64)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='invoices.movimentocontas')),
            ],
            options={
                'ordering': ['movimento_id', 'numero', 'id'],
                'constraints': [models.UniqueConstraint(fields=('movimento', 'numero'), name='uniq_parcela_movimento_numero'), models.CheckConstraint(condition=models.Q(('numero__gte', 1)), name='chk_parcela_numero_positivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='movimentocontas',
            constraint=models.UniqueConstraint(fields=('tipo', 'numero_documento'), name='uniq_movimento_tipo_numero_documento'),
        ),
    ]
