# Generated by Django 5.2.13 on 2026-05-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceextraction_movement_type_classificacao_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pessoa',
            name='chk_pessoa_is_cliente_bool',
        ),
        migrations.RemoveConstraint(
            model_name='pessoa',
            name='chk_pessoa_is_fornecedor_bool',
        ),
        migrations.RemoveConstraint(
            model_name='pessoa',
            name='chk_pessoa_is_faturado_bool',
        ),
    ]
